Metrics/LineLength:
  Max: 95

Metrics/AbcSize:  # Assignment Branch Condition size
  Max: 25

Metrics/MethodLength:
  Max: 15

Style/ParallelAssignment:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Description: 'Do not use prefix `_` for a variable that is used.'
  Enabled: false